Accounting:
  children:
    db_servers:
      hosts:
        DB:
          ansible_host: <PUBLIC_IP>
    lb_servers:
      hosts:
        LB:
          ansible_host: <PUBLIC_IP>
    web_servers:
      hosts:
        WEB:
          ansible_host: <PUBLIC_IP>
  vars:
    ansible_ssh_private_key_file: <KEY_PATH>
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    ansible_user: ubuntu
    app_name: Test
    db_port: 27017
    db_servers:
    - 192.168.0.13
    lb_port: 80
    web_server_port: 8080
    web_servers:
    - 192.168.0.12